name: cron_pressure_test

on:
  schedule:
    - cron: "*/5 * * * *"

env:
  GO111MODULE: on

jobs:
  build:
    name: Build_Deploy
    runs-on: [self-hosted, Linux, X64, deploy]
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      with:
          ref: merge-latest-ethereum
          submodules: true 

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
          
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    
    - name: Build
      run: make platon
    
    - name: Statistics_TPS
      run: bash /opt/statistics_tps.sh
    
    - name: Deploy_platon
      run: bash /opt/deploy_platon.sh
      
    - name: Deploy_transfer
      run: bash /opt/deploy_transfer.sh
